language: go

go:
  - 1.12.x

stages:
  - push

branches:
  only:
    - master
jobs:
  include:
    - stage: push
      script:
        - cd $HOME/gopath/src/github.com/integr8ly/manifests && make push/all QUAY_USERNAME=${QUAY_USERNAME} QUAY_PASSWORD=${QUAY_PASSWORD}"
