apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: keycloaks.aerogear.org
spec:
  group: aerogear.org
  names:
    kind: Keycloak
    listKind: KeycloakList
    plural: keycloaks
    singular: keycloak
  scope: Namespaced
  version: v1alpha1
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            version:
              type: string
            adminCredentials:
              type: string
            plugins:
              type: array
              items:
                description: Plugin names
                type: string
            backups:
              type: array
              items:
                description: Backup configuration
                type: object
            provision:
              type: boolean